version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stocking-order-report"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mp2gwq34cva4"
s3_prefix = "stocking-order-report"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
