AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'LOR Stocking Order'
Globals:
  Function:
    Timeout: 3

Resources:
  OrderReportFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies: AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
      Events:
        SignUp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /stocking/orders
            Method: get


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OrderReportApi:
    Description: "API Gateway endpoint URL for Prod stage for Signup function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/stocking/orders/"
  OrderReportFunction:
    Description: "Signup Lambda Function ARN"
    Value: !GetAtt OrderReportFunction.Arn
  OrderReportFunctionIamRole:
    Description: "Implicit IAM Role created for Signup function"
    Value: !GetAtt OrderReportFunctionRole.Arn
